export enum GamePhase {
    INITIALIZING = 'INITIALIZING',
    ROLLING = 'ROLLING',
    BETTING = 'BETTING',
    CHALLENGE_RESOLUTION = 'CHALLENGE_RESOLUTION',
    ROUND_CLOSED = 'ROUND_CLOSED',
    ROUND_END = 'ROUND_END',
    GAME_OVER = 'GAME_OVER'
} 